Task 62 added
ViktoriyaRyazhska/Java-Club-2 pull request #266
Opened 2021-08-24 10:54 UTC by Krip4yk-main

(same as 11, so it's an easy way to resolve)

2021-08-24 18:46 UTC, PavloSkolozdra requested changes

2021-08-24 18:46 UTC, PavloSkolozdra commented on javaClub/team3/Main.java
>  //        taskMap.put(63, new Task63());
new Task11 -> Task62

2021-08-24 18:47 UTC, Krip4yk-main commented on javaClub/team3/Main.java
>  //        taskMap.put(63, new Task63());
Не дуже зрозумів коментар

2021-08-24 19:23 UTC, Shum616 approved these changes

2021-08-24 19:24 UTC, PavloSkolozdra commented on javaClub/team3/Main.java
>  //        taskMap.put(63, new Task63());
У тебе в мапі ключ - число 62 а екземпляр створюється Task11 а не Task62

2021-08-25 04:52 UTC, Krip4yk-main commented on javaClub/team3/Main.java
>  //        taskMap.put(63, new Task63());
Я прокоментував в коміті чому так :) Завдання дублюється з 11м

2021-08-25 04:53 UTC, merged